# Generated by Django 5.2.6 on 2025-12-04 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_blogindexpage_blogpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Post Date, default=date.today",
            ),
            preserve_default=False,
        ),
    ]
