# Generated by Django 5.2.6 on 2025-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_blogpage_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
    ]
