# Generated by Django 5.2.6 on 2025-12-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_blogpagegalleryimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
    ]
