# Generated by Django 5.2.6 on 2025-01-20 10:00

from django.db import migrations, models
import datetime
from datetime import timedelta


def set_default_duration(apps, schema_editor):
    """Asigna una duración por defecto a las disciplinas existentes"""
    Disciplinas = apps.get_model('register_par', 'Disciplinas')
    for disciplina in Disciplinas.objects.all():
        disciplina.duracion_estimada = timedelta(hours=1)
        disciplina.save()


class Migration(migrations.Migration):

    dependencies = [
        ('register_par', '0004_alter_disciplinas_max_equipos_and_more'),
    ]

    operations = [
        # 1. Remover constraint existente de fechas (primero)
        migrations.RemoveConstraint(
            model_name='encuentros',
            name='check_fechas_encuentro',
        ),
        
        # 2. Remover campo rol de EncuentroEquipo (simple)
        migrations.RemoveField(
            model_name='encuentroequipo',
            name='rol',
        ),
        
        # 3. Hacer ffinEnc opcional (antes de agregar estado)
        migrations.AlterField(
            model_name='encuentros',
            name='ffinEnc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin:'),
        ),
        
        # 4. Agregar estado a encuentros
        migrations.AddField(
            model_name='encuentros',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADO', 'Finalizado')], default='CONFIRMADO', max_length=15, verbose_name='Estado del encuentro:'),
        ),
        
        # 5. Agregar duracion_estimada temporalmente como nullable
        migrations.AddField(
            model_name='disciplinas',
            name='duracion_estimada',
            field=models.DurationField(blank=True, null=True, verbose_name='Duración estimada del encuentro:'),
        ),
        
        # 6. Poblar el campo con valores por defecto
        migrations.RunPython(set_default_duration),
        
        # 7. Hacer el campo required
        migrations.AlterField(
            model_name='disciplinas',
            name='duracion_estimada',
            field=models.DurationField(default=timedelta(hours=1), verbose_name='Duración estimada del encuentro:'),
        ),
    ]