# Generated by Django 5.2.6 on 2025-10-21 16:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_par", "0006_add_fecha_constraint"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="encuentros",
            name="check_fechas_encuentro",
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="duracion_estimada",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                help_text="Formato: DD HH:MM:SS",
                verbose_name="Duración estimada del encuentro:",
            ),
        ),
        migrations.AlterField(
            model_name="participantes",
            name="equipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participantes",
                to="register_par.equipos",
                verbose_name="Equipo al que pertenece",
            ),
        ),
        migrations.AddConstraint(
            model_name="encuentros",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ffinEnc__gt", models.F("finiEnc")),
                    ("ffinEnc__isnull", True),
                    _connector="OR",
                ),
                name="check_fechas_encuentro",
            ),
        ),
    ]
