# Generated by Django 5.2.6 on 2025-10-21 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_par", "0007_add_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinas",
            name="duracion_estimada",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                verbose_name="Duración estimada del encuentro:",
            ),
        ),
    ]
