# Generated by Django 5.2.6 on 2025-10-21 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register_par", "0008_alter_disciplinas_duracion_estimada"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encuentroequipo",
            options={
                "verbose_name": "Equipo participante",
                "verbose_name_plural": "Equipos participantes",
            },
        ),
        migrations.AlterField(
            model_name="arbitros",
            name="idArb",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID:"
            ),
        ),
        migrations.AlterField(
            model_name="arbitros",
            name="nomArb",
            field=models.CharField(max_length=50, verbose_name="Nom. completo:"),
        ),
        migrations.AlterField(
            model_name="arbitros",
            name="telArb",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono de contacto sólo debe contener números.",
                        regex="^\\d+$",
                    )
                ],
                verbose_name="Teléfono de contacto:",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="idDis",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID:"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="max_equipos",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Máx. de equipos por encuentro:"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="max_participantes_por_equipo",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Máx. de participantes por equipo:"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="min_equipos",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Mín. de equipos por encuentro:"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="min_participantes_por_equipo",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Mín. de participantes por equipo:"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinas",
            name="nomDis",
            field=models.CharField(
                max_length=50, verbose_name="Nom. de la disciplina:"
            ),
        ),
        migrations.AlterField(
            model_name="encuentros",
            name="idEnc",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID:"
            ),
        ),
        migrations.AlterField(
            model_name="equipos",
            name="idEqu",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID:"
            ),
        ),
        migrations.AlterField(
            model_name="equipos",
            name="nomEqu",
            field=models.CharField(max_length=25, verbose_name="Nom. del equipo:"),
        ),
        migrations.AlterField(
            model_name="participantes",
            name="equipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participantes",
                to="register_par.equipos",
                verbose_name="Equipo asociado:",
            ),
        ),
        migrations.AlterField(
            model_name="participantes",
            name="idPar",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID:"
            ),
        ),
        migrations.AlterField(
            model_name="participantes",
            name="nomPar",
            field=models.CharField(max_length=75, verbose_name="Nom. completo:"),
        ),
        migrations.AlterField(
            model_name="participantes",
            name="telPar",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El teléfono de contacto sólo debe contener números.",
                        regex="^\\d+$",
                    )
                ],
                verbose_name="Teléfono de contacto:",
            ),
        ),
        migrations.AlterField(
            model_name="pistas",
            name="idPis",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID:"
            ),
        ),
        migrations.AlterField(
            model_name="pistas",
            name="nomPis",
            field=models.CharField(max_length=25, verbose_name="Nom. de la pista:"),
        ),
    ]
